name: my first pipeline #workflow name

on: push #event trigger

jobs:   #list of jobs
   first-job:  #job name
        runs-on: ubuntu-latest  #runs on ubuntu
        steps:  #steps to execute
          - name: checkout repo
            uses: actions/checkout@v4 #uses-- github marketplace action
          - name: welcome message
            run: echo "This is my first job"

          - name: list files
            run: ls

          - name: read file
            run: cat README.md 