name: my first pipeline #workflow name

on: push #event trigger

jobs:
   first-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            run: actions/checkout@v4
          - name: welcome message
            run: echo "This is my first job"

          - name: list files
            run: ls

          - name: read file
            run: cat README.md 